//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_BCN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class asientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asientos()
        {
            this.reservas_entradas = new HashSet<reservas_entradas>();
        }
    
        public int id_asiento { get; set; }
        public int numero { get; set; }
        public bool disponible { get; set; }
        public int id_evento { get; set; }
    
        public virtual eventos eventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservas_entradas> reservas_entradas { get; set; }
    }
}
