//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_BCN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class asientos
    {
        public int id_asiento { get; set; }
        public string numero { get; set; }
        public bool disponible { get; set; }
        public int id_evento { get; set; }


        public asientos(int id_asiento,string numero,bool disponible,int id_evento)
        {
            this.id_asiento = id_asiento;
            this.numero = numero;
            this.disponible = disponible;
            this.id_evento = id_evento;
        }
        public asientos(string numero, int id_evento)
        {
            disponible = false;
            this.numero = numero;
            this.id_evento = id_evento;
        }
        
    }
}
