//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_BCN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class chats
    {
        public int id_chat { get; set; }
        public int id_usuario_1 { get; set; }
        public int id_usuario_2 { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    }
}
