//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_BCN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventos
    {
        public int id_evento { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora_inicio { get; set; }
        public System.TimeSpan hora_fin { get; set; }
        public string lugar { get; set; }
        public decimal precio { get; set; }
        public int edad_minima { get; set; }
        public bool enumerado { get; set; }
        public int id_sala { get; set; }
    }
}
