//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_BCN.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CulturaBCNEntities : DbContext
    {
        public CulturaBCNEntities()
            : base("name=CulturaBCNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asientos> asientos { get; set; }
        public virtual DbSet<chats> chats { get; set; }
        public virtual DbSet<eventos> eventos { get; set; }
        public virtual DbSet<mensajes> mensajes { get; set; }
        public virtual DbSet<reservas_entradas> reservas_entradas { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<salas> salas { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
