//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_BCN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class salas
    {
        public salas(int total, string text1, string text2)
        {
            this.aforo = total;
            this.nombre = text1;
            this.direccion = text2;
        }
        public salas()
        {

        }
        public salas(int id_sala, string nombre, string direccion, int aforo) : this(aforo, nombre, direccion)
        {
            this.id_sala = id_sala;
        }

        public int id_sala { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public int aforo { get; set; }
    }
}
