//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_BCN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string correo { get; set; }
        public string contrasena_hash { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public Nullable<int> edad { get; set; }
        public string telefono { get; set; }
        public string foto_url { get; set; }
        public int id_rol { get; set; }
    }
}
